[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Регистрируем кастомные маркировки
markers =
    courses: Маркировка для тестов курсов
    dashboard: Маркировка для тестов, связанных с рабочей панелью
    authorization: Маркировка для тестов авторизации
    ui: Маркировка для UI тестов
    slow: Маркировка для медленных тестов
    smoke: Маркировка для smoke тестов
    critical: Маркировка для критичных тестов
    regression: Маркировка для регрессионных тестов.
    registration: Маркировка для тестов, связанных с регистрацией пользователей.